### ISSUE TITLE
CORS error when running build + artisan serve

### ISSUE THREAD

**Issue by devzom** [frizikk/laravel-nuxtjs-sanctum-fortify#1]
Thank You for this work & great example. :)

  there's a CORS issue when using SPA build and serve it by artisan serve

**Comment by frizikk** [comment]
Hi,

try to use http://localhost:8000/ instead of http://127.0.0.1:8000/

**Comment by devzom** [comment]
Yeap, it works, just wanted to point it out to fix in example. Thanks :)
